spring:
  application:
    name: library-api

  datasource:
      url: jdbc:postgresql://localhost:5433/dev_database
      driver-class-name: org.postgresql.Driver
      username: dev_user
      password: dev_password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        # 'update' is fine for dev, but consider 'validate' for production!
        ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          format_sql: true
