spring.application.name=ocado-library-backend


#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true

#TODO: DB now works locally, you have to create your own database or you can use the h2 setup.
spring.datasource.url=jdbc:postgresql://localhost:5432/ocado_library_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:changeInProd}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true