name: Run Backend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "zulu"
          cache: maven

      - name: Build backend tests
        working-directory: backend/ocado-library-backend
        run: mvn -B test

      # - name: Update dependency graph
      #   uses: advanced-security/maven-dependency-submission-action@v4
      #   with:
      #     directory: backend/ocado-library-backend
      #     ignore-maven-wrapper: true